name: CI

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            max-parallel: 4
            fail-fast: false
            
        steps:
        - uses: actions/checkout@v1
        - name: Install Dependencies
          run: |
            :
        - name: Set up Build
          run: |
            mkdir build
            cd build
            cmake ..
        - name: Build
          run: |
            cd build
            make
        - name: Tests
          run: |
            cd build
            ./test/KIClient_test
            
            
    cpplint:
        runs-on: ubuntu-latest
        strategy:
            max-parallel: 4
            fail-fast: false

        steps:
        - uses: actions/checkout@master
        - name: Set up Python
          uses: actions/setup-python@v1
          with:
            python-verion: 3.7
        - name: Install Dependencies
          run: |
            python -m pip install --upgrade pip
            pip install cpplint
        - name: Code Analysis
          run: |
            cpplint $(find . -name \*.h -or -name \*.cpp | grep -vE "^\.\/build\/")

